from tkinter import *
from tkinter  import  ttk, messagebox
import mysql.connector




def Delete(event):
     e1.delete(0, END)
     e2.delete(0, END)
     e3.delete(0, END)
     e4.delete(0, END)
     row_id = listbox.selection()[0]
     select = listbox.set(row_id)
     e1.insert(0,select['id'])
     e2.insert(0,select['stname'])
     e3.insert(0,select['coursename'])
     e4.insert(0,select['fee'])

def Add():
     id = e1.get()
     stname = e2.get()
     coursename = e3.get()
     fee = e4.get()

     mysqldb = mysql.connector.connect(host="localhost", user="root", password="eb20103023", database="python_video")
     mycursor = mysqldb.cursor()

     try:



         sql = "INSERT INTO user(id,stname,coursename,fee) VALUES (%s, %s, %s, %s)"
         val = (id,stname,coursename,fee)
         mycursor.execute(sql, val)
         mysqldb.commit()
         lastid = mycursor.lastrowid
         messagebox.showinfo("information", "Record inserted seccessfully...")

         e1.delete(0, END)
         e2.delete(0, END)
         e3.delete(0, END)
         e1.focus_set()
     except Exception as e:
         print(e)
         mysqldb.rollback()
         mysqldb.close()


def update():
    id = e1.get()
    stname = e2.get()
    coursename = e3.get()
    fee = e4.get()
    mysqldb = mysql.connector.connect(host="localhost", user="root", password="eb20103023", database="python_video")
    mycursor = mysqldb.cursor()

    try:
        sql = "Update user set id= %s,stname= %s,coursename= %s where fee= %s"
        val = (id,stname,coursename,fee)
        mycursor.execute(sql, val)
        mysqldb.commit()
        lastid = mycursor.lastrowid
        messagebox.showinfo("information", "Record updated successfully...")

        e1.delete(0, END)
        e2.delete(0, END)
        e3.delete(0, END)
        e4.delete(0, END)
        e1.focus_set()

    except Exception as e:

       print(e)
       mysqldb.rollback()
       mysqldb.close()

def delete():
     id = e1.get()

     mysqldb = mysql.connector.connect(host="localhost", user="root", password="eb20103023", database="python_video")
     mycursor = mysqldb.cursor()

     try:


         sql = "delete from user where id= %s"

         val = (id,)
         mycursor.execute(sql,val)
         mysqldb.commit()
         lastid = mycursor.lastrowid
         messagebox.showinfo("information","record Delete successfully...")

         e1.delete(0, END)
         e2.delete(0, END)
         e3.delete(0, END)
         e4.delete(0, END)
         e1.focus_set()


     except Exception as e:

         print(e)
         mysqldb.rollback()
         mysqldb.close()


def show():
    mysqldb = mysql.connector.connect(host="localhost", user="root", password="eb20103023", database="python_video")
    mycursor = mysqldb.cursor()



    mycursor = mysqldb.cursor()
    mycursor.execute("SELECT id,stname,coursename,fee FROM user")
    user = mycursor.fetchall()
    print(user)

    for i, (id,stname,coursename,fee) in enumerate(user, start=1):
         listbox.insert("","end",values=(id, stname, coursename, fee))
         mysqldb.close()

root = Tk()
root.geometry("600x300")
global e1
global e2
global e3
global e4



Label(root, text="Student Registeration", fg="blue",font=(None, 20)).place(x=300,y=5)

Label(root, text="Student ID").place(x=10, y=10)
Label(root, text="Student Name").place(x=10, y=38)
Label(root, text="Course").place(x=10, y=70)
Label(root, text ="Fee").place(x=10, y=100)


e1 = Entry(root)
e1.place(x=140, y=10)

e2 = Entry(root)
e2.place(x=140, y=40)

e3 = Entry(root)
e3.place(x=140, y=70)

e4 = Entry(root)
e4.place(x=140, y=100)



Button(root, text="Add",command = Add,height=3, width=13).place(x=30, y=130)

Button(root, text="Update",command = update,height=3, width=13).place(x=140, y=130)
Button(root, text="Delete",command = delete,height=3, width=13).place(x=250, y=130)







root.mainloop()
